import { useEffect, useState } from 'react';
import type { NetworkProfile, NetworkSnapshot, Provider } from '../../../shared/contracts';
const states={stopped:'Arrêté',starting:'Démarrage…',owned:'Lancé par Lullaby · port joignable',external:'Relais externe détecté · conservé',error:'Démarrage échoué'};
export function NetworkSettings({onClose}:{onClose:()=>void}){
  const [data,setData]=useState<NetworkSnapshot>();const [selected,setSelected]=useState<Provider>('claude');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const [url,setUrl]=useState('');const [certificate,setCertificate]=useState('');const [executable,setExecutable]=useState('');const [args,setArgs]=useState('');const [host,setHost]=useState('127.0.0.1');const [port,setPort]=useState('');
  async function refresh(){const result=await window.lullaby.networkSettings();if(result.ok)setData(result.value);else setMessage(result.message);}
  useEffect(()=>{void refresh();},[]);
  useEffect(()=>{const profile=data?.profiles.find(p=>p.provider===selected);setUrl(profile?.proxyUrl??'');setCertificate(profile?.certificatePath??'');setExecutable(profile?.launcher?.executable??'');setArgs(profile?.launcher?.args.join('\n')??'');setHost(profile?.launcher?.host??'127.0.0.1');setPort(profile?.launcher?.port.toString()??'');},[selected,data]);
  function profile():NetworkProfile{return {provider:selected,...(url.trim()?{proxyUrl:url.trim()}:{}),...(certificate.trim()?{certificatePath:certificate.trim()}:{}),...(executable.trim()?{launcher:{executable:executable.trim(),args:args.split('\n').filter(Boolean),host:host.trim(),port:Number(port)}}:{})};}
  async function act(action:'save'|'start'|'stop'){
    setBusy(true);setMessage('');try{
      if(action!=='stop'){const result=await window.lullaby.saveNetworkProfile(profile());if(!result.ok){setMessage(result.message);return;}}
      if(action!=='save'){const result=await (action==='start'?window.lullaby.startProxy(selected):window.lullaby.stopProxy(selected));if(!result.ok){setMessage(result.message);return;}setMessage(states[result.value]);}else setMessage('Réglages enregistrés. Ils s’appliquent au prochain lancement du moteur.');
      await refresh();
    }catch{setMessage('Le réglage réseau n’a pas pu être appliqué.');}finally{setBusy(false);}
  }
  const state=data?.states[selected]??'stopped';const owned=['owned','starting'].includes(state);
  return <aside className="settings-panel" aria-label="Réseau et relais"><div className="panel-heading"><h2>Réseau & relais</h2><button className="secondary" onClick={onClose}>Fermer</button></div><p>Chaque moteur garde ses réglages. Aucun relais n’est nécessaire sur un réseau qui fonctionne déjà.</p><label>Moteur<select value={selected} disabled={busy} onChange={e=>setSelected(e.target.value as Provider)}><option value="claude">Claude Code</option><option value="codex">Codex</option></select></label>
    <form className="network-form" onSubmit={e=>{e.preventDefault();void act('save');}}><fieldset disabled={busy||owned}><label>Adresse du proxy HTTP(S)<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Vide : réglage hérité"/></label><label>Certificat d’entreprise (fichier PEM)<input value={certificate} onChange={e=>setCertificate(e.target.value)} placeholder="Vide : réglage hérité"/></label><p className="field-hint">Certificat transmis via {selected==='claude'?'NODE_EXTRA_CA_CERTS':'CODEX_CA_CERTIFICATE'}. Les variables existantes restent héritées si le champ est vide.</p><details><summary>Configurer le lancement du relais</summary><p>Renseignez la commande validée sur votre poste. Px n’est pas installé automatiquement. N’inscrivez aucun mot de passe ou jeton.</p><label>Exécutable Windows<input value={executable} onChange={e=>setExecutable(e.target.value)} placeholder="Chemin de px.exe"/></label><label>Arguments · un argument par ligne<textarea value={args} onChange={e=>setArgs(e.target.value)} rows={3}/></label><div className="network-listener"><label>Écoute locale<input value={host} onChange={e=>setHost(e.target.value)}/></label><label>Port<input type="number" min="1" max="65535" value={port} onChange={e=>setPort(e.target.value)}/></label></div></details><button className="primary">Enregistrer</button></fieldset></form>
    <section className="diagnostic-card"><h3>Relais local</h3><p>{states[state]}</p><div className="button-row"><button className="secondary" disabled={busy||owned||!executable||!port} onClick={()=>void act('start')}>{executable?'Enregistrer et lancer':'Configurer le relais'}</button><button className="secondary" disabled={busy||state!=='owned'} onClick={()=>void act('stop')}>Arrêter</button></div><p className="field-hint">Un port joignable ne prouve pas que Claude ou Codex atteint son service. Vérifiez ensuite le moteur et envoyez un message d’essai.</p></section>
    <details className="inherited"><summary>Environnement hérité · présence uniquement</summary>{data?.inherited.map(item=><p key={item.name}>{item.name} : {item.present?'présente':'absente'}</p>)}</details>{message&&<p className="notice" role="status">{message}</p>}
  </aside>;
}
