import { useEffect,useState } from 'react';
import type { Diagnostic } from '../../../shared/contracts';
import { Diagnostics } from './Diagnostics';
import { NetworkSettings } from './NetworkSettings';
import { UiIcon,ProviderLogo } from '../app/UiIcon';
export function SettingsScreen({items,loading,onRefresh,onClose}:{items:Diagnostic[];loading:boolean;onRefresh:()=>void;onClose:()=>void}){
  const [tab,setTab]=useState<'engines'|'network'|'appearance'>('engines');const [path,setPath]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  const [motion,setMotion]=useState(()=>localStorage.getItem('lullaby.motion')!=='off');
  const [size,setSize]=useState(()=>{const stored=localStorage.getItem('lullaby.text-size');return stored==='15'?'14':stored==='17'?'16':stored&&['13','14','16'].includes(stored)?stored:'14';});
  useEffect(()=>{void window.lullaby.engineSettings().then(result=>{if(result.ok)setPath(result.value.codexExecutable??'');else setMessage(result.message);});},[]);
  useEffect(()=>{const listener=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[onClose]);
  async function save(){setBusy(true);setMessage('');try{const result=await window.lullaby.saveEngineSettings(path.trim()?{codexExecutable:path.trim()}:{});if(result.ok){setMessage('Moteur enregistré.');onRefresh();}else setMessage(result.message);}catch{setMessage('Impossible d’enregistrer le moteur.');}finally{setBusy(false);}}
  return <div className="settings-backdrop"><section className="settings-screen" role="dialog" aria-modal="true" aria-label="Paramètres"><header className="settings-title"><UiIcon name="settings"/><h2>Paramètres</h2><button className="icon-button" aria-label="Fermer les paramètres" onClick={onClose}><UiIcon name="close"/></button></header><div className="settings-body"><nav aria-label="Catégories des paramètres">{([{id:'engines',label:'Moteurs',icon:'settings'},{id:'network',label:'Réseau',icon:'network'},{id:'appearance',label:'Apparence',icon:'preview'}]as const).map(item=><button key={item.id} aria-current={tab===item.id?'page':undefined} onClick={()=>setTab(item.id)}><UiIcon name={item.icon}/>{item.label}</button>)}</nav><div className="settings-content">
    {tab==='engines'&&<><h2>Moteurs & abonnements</h2><p>Vos sessions utilisent les connexions des outils officiels installés sur ce poste.</p><section className="diagnostic-card"><h3><ProviderLogo provider="codex"/> Codex · ChatGPT</h3><label>Exécutable Codex<input aria-label="Exécutable Codex" value={path} onChange={e=>setPath(e.target.value)} placeholder="Détection automatique"/></label><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>void window.lullaby.pickCodexExecutable().then(result=>{if(result.ok&&result.value)setPath(result.value);else if(!result.ok)setMessage(result.message);})}>Parcourir…</button><button className="secondary" onClick={()=>setPath('')}>Automatique</button><button className="primary" disabled={busy} onClick={()=>void save()}>Enregistrer</button></div><p className="field-hint">Chemin vide : recherche dans le PATH et l’installation officielle de Codex. Pour une nouvelle connexion, utilisez « codex login » dans la CLI officielle, puis vérifiez à nouveau.</p></section>{message&&<p className="notice" role="status">{message}</p>}<Diagnostics items={items} loading={loading} onRefresh={onRefresh} onClose={onClose}/>{!items.length&&<p className="field-hint">Ouvrez un projet pour vérifier la connexion et les capacités dans son dossier.</p>}</>}
    {tab==='network'&&<NetworkSettings onClose={onClose}/>}
    {tab==='appearance'&&<><h2>Apparence</h2><section className="diagnostic-card"><h3>Iris</h3><p>Lavande, menthe et ambre. Les emblèmes restent stables pour chaque projet.</p><label className="setting-toggle"><input type="checkbox" checked={motion} onChange={e=>{setMotion(e.target.checked);localStorage.setItem('lullaby.motion',e.target.checked?'on':'off');document.documentElement.dataset.motion=e.target.checked?'on':'off';}}/>Animations discrètes</label><label>Taille du texte des conversations<select value={size} onChange={e=>{setSize(e.target.value);localStorage.setItem('lullaby.text-size',e.target.value);document.documentElement.style.setProperty('--chat-font',`${e.target.value}px`);}}><option value="13">Compacte</option><option value="14">Standard</option><option value="16">Grande</option></select></label></section><section className="diagnostic-card"><h3>Données locales</h3><p>Conversations et brouillons : %APPDATA%\lullaby\state.json. Le dossier du projet garde vos fichiers ; retirer un projet de Lullaby ne les supprime pas.</p></section></>}
  </div></div></section></div>;
}
