import { useContext, useState } from 'react';
import type { Diagnostic, Project, Provider, Session } from '../../../shared/contracts';
import { SnapshotContext } from '../chat/sessionStore';
import { SessionChat } from '../chat/SessionChat';
export const phaseLabel={idle:'Prêt',running:'Travaille',waiting:'Votre réponse',done:'Terminé',interrupted:'Interrompu',error:'À vérifier'};
export function ProjectSessions({project,selected,onSelect,diagnostics,onError}:{project:Project;selected?:string;onSelect:(id:string)=>void;diagnostics:Diagnostic[];onError:(message:string)=>void}){
  const snapshot=useContext(SnapshotContext);const sessions=snapshot.sessions.filter(s=>s.projectId===project.id);
  const session=sessions.find(s=>s.id===selected);const [creating,setCreating]=useState(false);const [native,setNative]=useState('');const [provider,setProvider]=useState<Provider>('claude');
  async function create(provider:Provider,nativeId?:string){setCreating(true);try{const result=await window.lullaby.createSession(project.id,provider,nativeId);if(result.ok){onSelect(result.value.id);setNative('');}else onError(result.message);}finally{setCreating(false);}}
  return <div className="project-studio"><aside className="sessions-list"><div className="eyebrow">CONVERSATIONS <span>{sessions.length}</span></div><div className="new-session"><button className="secondary" disabled={creating} onClick={()=>void create('claude')}>＋ Claude</button><button className="secondary" disabled={creating} onClick={()=>void create('codex')}>＋ Codex</button></div>
    <nav aria-label="Conversations">{sessions.map(item=><button key={item.id} className={`session-card ${selected===item.id?'selected':''}`} onClick={()=>onSelect(item.id)}><span className="session-provider">{item.provider==='claude'?'Claude Code':'Codex'}</span><strong>{item.title}</strong><span className={`phase ${item.phase}`}>{phaseLabel[item.phase]}</span></button>)}</nav>
    <details className="import-session"><summary>Reprendre depuis la CLI</summary><p>Utilisez le même dossier et fermez d’abord la session dans l’autre client. L’historique antérieur reste dans le moteur ; le chat affiche les nouveaux échanges.</p><form onSubmit={e=>{e.preventDefault();void create(provider,native.trim());}}><label>Moteur<select value={provider} onChange={e=>setProvider(e.target.value as Provider)}><option value="claude">Claude Code</option><option value="codex">Codex</option></select></label><label>Identifiant natif<input value={native} onChange={e=>setNative(e.target.value)} placeholder="UUID de la session" required/></label><button className="secondary" disabled={creating||!native.trim()}>Reprendre</button></form></details>
  </aside><section className="conversation">{session?<><SessionHeader session={session} diagnostic={diagnostics.find(d=>d.provider===session.provider)} onError={onError}/><SessionChat key={session.id} sessionId={session.id}/></>:<div className="chat-empty"><div className="eyebrow">UN PROJET, PLUSIEURS CONVERSATIONS</div><h2>Choisissez votre premier agent.</h2><p>Créez une conversation Claude ou Codex pour commencer à travailler.</p><p>Une exécution à la fois dans ce dossier ; les autres projets restent disponibles.</p></div>}</section></div>;
}
function SessionHeader({session,diagnostic,onError}:{session:Session;diagnostic?:Diagnostic;onError:(message:string)=>void}){
  const running=['running','waiting'].includes(session.phase);const model=diagnostic?.models?.find(model=>model.id===session.choices.model);
  async function configure(key:'model'|'effort',value:string){const next={...session.choices};if(value)next[key]=value;else delete next[key];if(key==='model')delete next.effort;const result=await window.lullaby.configureSession(session.id,next);if(!result.ok)onError(result.message);}
  return <header className="session-header"><div><span className="session-provider">{session.provider==='claude'?'Claude Code':'Codex'}</span><h2>{session.title}</h2></div><span className={`phase ${session.phase}`}>{phaseLabel[session.phase]}</span><div className="session-options"><label>Modèle<select aria-label="Modèle" disabled={running} value={session.choices.model??''} onChange={e=>void configure('model',e.target.value)}><option value="">Réglage natif{diagnostic?.configuredModel?` · ${diagnostic.configuredModel}`:''}</option>{diagnostic?.models?.map(model=><option key={model.id} value={model.id}>{model.name}</option>)}{session.choices.model&&!model&&<option value={session.choices.model}>{session.choices.model}</option>}</select></label><label>Effort<select aria-label="Effort" disabled={running||!model?.efforts.length} value={session.choices.effort??''} onChange={e=>void configure('effort',e.target.value)}><option value="">Réglage natif</option>{model?.efforts.map(effort=><option key={effort} value={effort}>{effort}</option>)}</select></label></div>{diagnostic?.issues.map(issue=><p className="model-notice" key={issue}>{issue}</p>)}</header>;
}
